from errors import MSE, SSE
from linear_np import normalEquationRegression, gradientDescentRegression, gradientDescentAutogradRegression
from linear_torch import TorchNormalEquationRegression, TorchGradientDescentRegression, TorchGradientDescentAutogradRegression