from errors import MSE, SSE, MSE_torch, SSE_torch
from linear_np import normalEquationRegression, gradientDescentRegression, gradientDescentAutogradRegression
from linear_torch import TorchNormalEquationRegression, TorchGradientDescentRegression, TorchGradientDescentAutogradRegression